import { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { Calculator, Share2, Download, Flame, Drumstick, Wheat, Droplet, Crown, Save, HelpCircle, Lock } from 'lucide-react';
import { Button } from './ui/button';
import { Input } from './ui/input';
import { Label } from './ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from './ui/select';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from './ui/card';
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from './ui/tooltip';
import { toast } from 'sonner';

interface CalorieResult {
  calories: number;
  protein: number;
  carbs: number;
  fats: number;
  bmr: number;
}

interface CalorieCalculatorProps {
  isLoggedIn: boolean;
  onOpenAuth: () => void;
  onOpenPremium: () => void;
}

export function CalorieCalculator({ isLoggedIn, onOpenAuth, onOpenPremium }: CalorieCalculatorProps) {
  const [formData, setFormData] = useState({
    age: '',
    gender: '',
    weight: '',
    height: '',
    activityLevel: '',
    goal: '',
  });

  const [results, setResults] = useState<CalorieResult | null>(null);
  const [isCalculating, setIsCalculating] = useState(false);
  const [savedCount, setSavedCount] = useState(0);

  const tooltips = {
    age: 'Your age helps determine your basal metabolic rate (BMR), which naturally decreases as we age.',
    gender: 'Biological sex affects muscle mass and metabolism. Men typically have higher BMR due to greater muscle mass.',
    weight: 'Your current body weight in kilograms. This is a key factor in calculating your daily calorie needs.',
    height: 'Your height in centimeters. Combined with weight, this helps assess your body composition.',
    activity: 'How active you are daily. More activity means more calories burned and higher calorie needs.',
    goal: 'Whether you want to lose, maintain, or gain weight. This adjusts your calorie target accordingly.',
  };

  const calculateCalories = () => {
    const { age, gender, weight, height, activityLevel, goal } = formData;

    if (!age || !gender || !weight || !height || !activityLevel || !goal) {
      toast.error('Please fill in all fields');
      return;
    }

    setIsCalculating(true);

    // Simulate calculation delay for smooth animation
    setTimeout(() => {
      const weightKg = parseFloat(weight);
      const heightCm = parseFloat(height);
      const ageYears = parseFloat(age);

      let bmr: number;
      if (gender === 'male') {
        bmr = 10 * weightKg + 6.25 * heightCm - 5 * ageYears + 5;
      } else {
        bmr = 10 * weightKg + 6.25 * heightCm - 5 * ageYears - 161;
      }

      const activityMultipliers: { [key: string]: number } = {
        sedentary: 1.2,
        light: 1.375,
        moderate: 1.55,
        active: 1.725,
        veryActive: 1.9,
      };

      const tdee = bmr * activityMultipliers[activityLevel];

      let calories: number;
      if (goal === 'lose') {
        calories = tdee - 500;
      } else if (goal === 'gain') {
        calories = tdee + 300;
      } else {
        calories = tdee;
      }

      const protein = Math.round((calories * 0.28) / 4);
      const carbs = Math.round((calories * 0.45) / 4);
      const fats = Math.round((calories * 0.27) / 9);

      setResults({
        calories: Math.round(calories),
        protein,
        carbs,
        fats,
        bmr: Math.round(bmr),
      });

      setIsCalculating(false);
      toast.success('Calculation complete!');
    }, 1000);
  };

  const handleSave = () => {
    if (!isLoggedIn) {
      toast.error('Please login to save results');
      onOpenAuth();
      return;
    }

    if (savedCount >= 3) {
      toast.error('Free users can save up to 3 calculations');
      onOpenPremium();
      return;
    }

    setSavedCount(savedCount + 1);
    toast.success('Results saved to your account!');
  };

  const handleShare = () => {
    if (!results) return;
    
    const shareText = `My daily calorie target: ${results.calories} kcal\nProtein: ${results.protein}g | Carbs: ${results.carbs}g | Fats: ${results.fats}g`;
    
    if (navigator.share) {
      navigator.share({
        title: 'My Calorie Calculation - FitCalc',
        text: shareText,
      }).catch(() => {});
    } else {
      navigator.clipboard.writeText(shareText);
      toast.success('Results copied to clipboard!');
    }
  };

  const handleDownload = () => {
    if (!results) return;
    
    const content = `
CALORIE CALCULATION RESULTS
============================

Daily Calorie Target: ${results.calories} kcal
Basal Metabolic Rate: ${results.bmr} kcal

MACRONUTRIENTS:
- Protein: ${results.protein}g
- Carbohydrates: ${results.carbs}g
- Fats: ${results.fats}g

Generated by FitCalc
${new Date().toLocaleDateString()}
`;
    
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `fitcalc-results-${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    
    toast.success('Results downloaded!');
  };

  return (
    <div className="min-h-screen py-12">
      <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Ad Banner Placeholder */}
        <motion.div
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          className="mb-8"
        >
          <div className="bg-gradient-to-r from-gray-100 to-gray-200 rounded-2xl p-6 text-center border-2 border-dashed border-gray-300">
            <p className="text-gray-500">Advertisement Space - 728x90</p>
          </div>
        </motion.div>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="text-center mb-12"
        >
          <div className="inline-flex items-center gap-2 bg-green-100 text-green-700 px-4 py-2 rounded-full mb-4">
            <Calculator className="w-4 h-4" />
            <span>Calorie Calculator</span>
          </div>
          <h1 className="text-gray-900 mb-4">
            Calculate Your Daily Calorie Needs
          </h1>
          <p className="text-gray-600 max-w-2xl mx-auto">
            Get personalized calorie and macronutrient recommendations based on your
            unique profile and fitness goals.
          </p>
        </motion.div>

        <div className="grid lg:grid-cols-2 gap-8">
          {/* Input Form */}
          <motion.div
            initial={{ opacity: 0, x: -30 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: 0.2 }}
          >
            <Card className="shadow-lg">
              <CardHeader>
                <CardTitle>Your Information</CardTitle>
                <CardDescription>
                  Enter your details to calculate your calorie needs
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-6">
                <TooltipProvider>
                  <div className="grid sm:grid-cols-2 gap-4">
                    <div className="space-y-2">
                      <Label htmlFor="age" className="flex items-center gap-2">
                        Age
                        <Tooltip>
                          <TooltipTrigger asChild>
                            <HelpCircle className="w-4 h-4 text-gray-400 cursor-help" />
                          </TooltipTrigger>
                          <TooltipContent>
                            <p className="max-w-xs">{tooltips.age}</p>
                          </TooltipContent>
                        </Tooltip>
                      </Label>
                      <motion.div whileFocus={{ scale: 1.02 }}>
                        <Input
                          id="age"
                          type="number"
                          placeholder="25"
                          value={formData.age}
                          onChange={(e) => setFormData({ ...formData, age: e.target.value })}
                        />
                      </motion.div>
                    </div>

                    <div className="space-y-2">
                      <Label htmlFor="gender" className="flex items-center gap-2">
                        Gender
                        <Tooltip>
                          <TooltipTrigger asChild>
                            <HelpCircle className="w-4 h-4 text-gray-400 cursor-help" />
                          </TooltipTrigger>
                          <TooltipContent>
                            <p className="max-w-xs">{tooltips.gender}</p>
                          </TooltipContent>
                        </Tooltip>
                      </Label>
                      <Select
                        value={formData.gender}
                        onValueChange={(value) => setFormData({ ...formData, gender: value })}
                      >
                        <SelectTrigger id="gender">
                          <SelectValue placeholder="Select" />
                        </SelectTrigger>
                        <SelectContent>
                          <SelectItem value="male">Male</SelectItem>
                          <SelectItem value="female">Female</SelectItem>
                        </SelectContent>
                      </Select>
                    </div>
                  </div>

                  <div className="grid sm:grid-cols-2 gap-4">
                    <div className="space-y-2">
                      <Label htmlFor="weight" className="flex items-center gap-2">
                        Weight (kg)
                        <Tooltip>
                          <TooltipTrigger asChild>
                            <HelpCircle className="w-4 h-4 text-gray-400 cursor-help" />
                          </TooltipTrigger>
                          <TooltipContent>
                            <p className="max-w-xs">{tooltips.weight}</p>
                          </TooltipContent>
                        </Tooltip>
                      </Label>
                      <motion.div whileFocus={{ scale: 1.02 }}>
                        <Input
                          id="weight"
                          type="number"
                          placeholder="70"
                          value={formData.weight}
                          onChange={(e) => setFormData({ ...formData, weight: e.target.value })}
                        />
                      </motion.div>
                    </div>

                    <div className="space-y-2">
                      <Label htmlFor="height" className="flex items-center gap-2">
                        Height (cm)
                        <Tooltip>
                          <TooltipTrigger asChild>
                            <HelpCircle className="w-4 h-4 text-gray-400 cursor-help" />
                          </TooltipTrigger>
                          <TooltipContent>
                            <p className="max-w-xs">{tooltips.height}</p>
                          </TooltipContent>
                        </Tooltip>
                      </Label>
                      <motion.div whileFocus={{ scale: 1.02 }}>
                        <Input
                          id="height"
                          type="number"
                          placeholder="175"
                          value={formData.height}
                          onChange={(e) => setFormData({ ...formData, height: e.target.value })}
                        />
                      </motion.div>
                    </div>
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor="activity" className="flex items-center gap-2">
                      Activity Level
                      <Tooltip>
                        <TooltipTrigger asChild>
                          <HelpCircle className="w-4 h-4 text-gray-400 cursor-help" />
                        </TooltipTrigger>
                        <TooltipContent>
                          <p className="max-w-xs">{tooltips.activity}</p>
                        </TooltipContent>
                      </Tooltip>
                    </Label>
                    <Select
                      value={formData.activityLevel}
                      onValueChange={(value) => setFormData({ ...formData, activityLevel: value })}
                    >
                      <SelectTrigger id="activity">
                        <SelectValue placeholder="Select your activity level" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="sedentary">Sedentary (little or no exercise)</SelectItem>
                        <SelectItem value="light">Light (exercise 1-3 days/week)</SelectItem>
                        <SelectItem value="moderate">Moderate (exercise 3-5 days/week)</SelectItem>
                        <SelectItem value="active">Active (exercise 6-7 days/week)</SelectItem>
                        <SelectItem value="veryActive">Very Active (intense exercise daily)</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor="goal" className="flex items-center gap-2">
                      Goal
                      <Tooltip>
                        <TooltipTrigger asChild>
                          <HelpCircle className="w-4 h-4 text-gray-400 cursor-help" />
                        </TooltipTrigger>
                        <TooltipContent>
                          <p className="max-w-xs">{tooltips.goal}</p>
                        </TooltipContent>
                      </Tooltip>
                    </Label>
                    <Select
                      value={formData.goal}
                      onValueChange={(value) => setFormData({ ...formData, goal: value })}
                    >
                      <SelectTrigger id="goal">
                        <SelectValue placeholder="Select your goal" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="lose">Lose Weight</SelectItem>
                        <SelectItem value="maintain">Maintain Weight</SelectItem>
                        <SelectItem value="gain">Gain Weight</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                </TooltipProvider>

                <Button
                  onClick={calculateCalories}
                  disabled={isCalculating}
                  className="w-full bg-gradient-to-r from-green-600 to-emerald-600 hover:from-green-700 hover:to-emerald-700 text-white rounded-full"
                  size="lg"
                >
                  {isCalculating ? (
                    <>
                      <motion.div
                        animate={{ rotate: 360 }}
                        transition={{ duration: 1, repeat: Infinity, ease: 'linear' }}
                        className="w-5 h-5 border-2 border-white border-t-transparent rounded-full mr-2"
                      />
                      Calculating...
                    </>
                  ) : (
                    <>
                      <Calculator className="w-5 h-5 mr-2" />
                      Calculate
                    </>
                  )}
                </Button>
              </CardContent>
            </Card>
          </motion.div>

          {/* Results */}
          <motion.div
            initial={{ opacity: 0, x: 30 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: 0.3 }}
          >
            <AnimatePresence mode="wait">
              {results ? (
                <motion.div
                  key="results"
                  initial={{ opacity: 0, scale: 0.9 }}
                  animate={{ opacity: 1, scale: 1 }}
                  exit={{ opacity: 0, scale: 0.9 }}
                  className="space-y-6"
                >
                  <Card className="shadow-lg bg-gradient-to-br from-green-50 to-emerald-50 border-green-200">
                    <CardHeader>
                      <CardTitle className="flex items-center gap-2">
                        <Flame className="w-6 h-6 text-orange-500" />
                        Your Daily Calorie Target
                      </CardTitle>
                    </CardHeader>
                    <CardContent>
                      <div className="text-center">
                        <motion.div
                          initial={{ scale: 0 }}
                          animate={{ scale: 1 }}
                          transition={{ type: 'spring', delay: 0.2 }}
                          className="bg-gradient-to-r from-green-600 to-emerald-600 bg-clip-text text-transparent mb-2"
                        >
                          {results.calories}
                        </motion.div>
                        <p className="text-gray-600">calories per day</p>
                        <div className="mt-4 pt-4 border-t border-green-200">
                          <p className="text-gray-600">
                            Basal Metabolic Rate: {results.bmr} kcal
                          </p>
                        </div>
                      </div>
                    </CardContent>
                  </Card>

                  <Card className="shadow-lg">
                    <CardHeader>
                      <CardTitle>Macronutrient Breakdown</CardTitle>
                      <CardDescription>
                        Daily recommended intake
                      </CardDescription>
                    </CardHeader>
                    <CardContent className="space-y-4">
                      <motion.div
                        initial={{ opacity: 0, x: -20 }}
                        animate={{ opacity: 1, x: 0 }}
                        transition={{ delay: 0.3 }}
                        className="flex items-center justify-between p-4 bg-orange-50 rounded-xl"
                      >
                        <div className="flex items-center gap-3">
                          <div className="bg-orange-500 p-2 rounded-lg">
                            <Drumstick className="w-5 h-5 text-white" />
                          </div>
                          <div>
                            <p className="text-gray-600">Protein</p>
                            <p className="text-orange-600">{results.protein}g</p>
                          </div>
                        </div>
                        <div className="text-orange-600">
                          {Math.round((results.protein * 4 / results.calories) * 100)}%
                        </div>
                      </motion.div>

                      <motion.div
                        initial={{ opacity: 0, x: -20 }}
                        animate={{ opacity: 1, x: 0 }}
                        transition={{ delay: 0.4 }}
                        className="flex items-center justify-between p-4 bg-blue-50 rounded-xl"
                      >
                        <div className="flex items-center gap-3">
                          <div className="bg-blue-500 p-2 rounded-lg">
                            <Wheat className="w-5 h-5 text-white" />
                          </div>
                          <div>
                            <p className="text-gray-600">Carbohydrates</p>
                            <p className="text-blue-600">{results.carbs}g</p>
                          </div>
                        </div>
                        <div className="text-blue-600">
                          {Math.round((results.carbs * 4 / results.calories) * 100)}%
                        </div>
                      </motion.div>

                      <motion.div
                        initial={{ opacity: 0, x: -20 }}
                        animate={{ opacity: 1, x: 0 }}
                        transition={{ delay: 0.5 }}
                        className="flex items-center justify-between p-4 bg-amber-50 rounded-xl"
                      >
                        <div className="flex items-center gap-3">
                          <div className="bg-amber-500 p-2 rounded-lg">
                            <Droplet className="w-5 h-5 text-white" />
                          </div>
                          <div>
                            <p className="text-gray-600">Fats</p>
                            <p className="text-amber-600">{results.fats}g</p>
                          </div>
                        </div>
                        <div className="text-amber-600">
                          {Math.round((results.fats * 9 / results.calories) * 100)}%
                        </div>
                      </motion.div>
                    </CardContent>
                  </Card>

                  <div className="grid grid-cols-3 gap-3">
                    <Button
                      onClick={handleSave}
                      variant="outline"
                      className="rounded-full border-2 flex-col h-auto py-3"
                    >
                      {isLoggedIn ? <Save className="w-5 h-5 mb-1" /> : <Lock className="w-5 h-5 mb-1" />}
                      <span>Save</span>
                    </Button>
                    <Button
                      onClick={handleShare}
                      variant="outline"
                      className="rounded-full border-2 flex-col h-auto py-3"
                    >
                      <Share2 className="w-5 h-5 mb-1" />
                      <span>Share</span>
                    </Button>
                    <Button
                      onClick={handleDownload}
                      variant="outline"
                      className="rounded-full border-2 flex-col h-auto py-3"
                    >
                      <Download className="w-5 h-5 mb-1" />
                      <span>Download</span>
                    </Button>
                  </div>

                  {/* Premium Upsell */}
                  <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 0.6 }}
                  >
                    <Card className="bg-gradient-to-br from-amber-50 to-orange-50 border-amber-200 shadow-lg cursor-pointer hover:shadow-xl transition-shadow" onClick={onOpenPremium}>
                      <CardContent className="p-6">
                        <div className="flex items-center gap-4">
                          <div className="bg-gradient-to-br from-amber-500 to-orange-600 p-3 rounded-xl">
                            <Crown className="w-6 h-6 text-white" />
                          </div>
                          <div className="flex-1">
                            <h3 className="text-gray-900 mb-1">Upgrade to Premium</h3>
                            <p className="text-gray-600">
                              Get unlimited calculations, meal plans, and more!
                            </p>
                          </div>
                          <Button className="bg-gradient-to-r from-amber-600 to-orange-600 hover:from-amber-700 hover:to-orange-700 text-white rounded-full">
                            Upgrade
                          </Button>
                        </div>
                      </CardContent>
                    </Card>
                  </motion.div>
                </motion.div>
              ) : (
                <Card className="shadow-lg h-full flex items-center justify-center">
                  <CardContent className="text-center py-12">
                    <motion.div
                      animate={{ 
                        scale: [1, 1.1, 1],
                        rotate: [0, 5, -5, 0]
                      }}
                      transition={{ 
                        duration: 2,
                        repeat: Infinity,
                        repeatType: 'reverse'
                      }}
                      className="bg-gray-100 w-20 h-20 rounded-full flex items-center justify-center mx-auto mb-4"
                    >
                      <Calculator className="w-10 h-10 text-gray-400" />
                    </motion.div>
                    <h3 className="text-gray-900 mb-2">Ready to Calculate</h3>
                    <p className="text-gray-600 max-w-sm">
                      Fill in your information and click calculate to see your personalized
                      calorie and macronutrient recommendations.
                    </p>
                  </CardContent>
                </Card>
              )}
            </AnimatePresence>
          </motion.div>
        </div>

        {/* Ad Banner Placeholder Bottom */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.4 }}
          className="mt-12"
        >
          <div className="bg-gradient-to-r from-gray-100 to-gray-200 rounded-2xl p-8 text-center border-2 border-dashed border-gray-300">
            <p className="text-gray-500">Advertisement Space - 970x90</p>
          </div>
        </motion.div>
      </div>
    </div>
  );
}
